// Copyright 2006-2022 ClickTale Ltd., US Patent Pending

window.ClickTaleGlobal = window.ClickTaleGlobal || {};
window.ClickTaleSettings = window.ClickTaleSettings || {};

ClickTaleGlobal.init = ClickTaleGlobal.init || {};
ClickTaleGlobal.scripts = ClickTaleGlobal.scripts || {};

ClickTaleGlobal.scripts.filter = ClickTaleGlobal.scripts.filter || (function () {
	var recordingThreshold = Math.random() * 100;

	return {
		isRecordingApproved: function(percentage) {
			return recordingThreshold <= percentage;
		}
	}
})();
	
		
// Copyright 2006-2022 ClickTale Ltd., US Patent Pending
// PID: 82



/*browsers exclusion start*/ ClickTaleSettings.PTC.doOnlyWhen = function (toDoHandler, toCheckHandler, interval, times, failHandler) {
            if ((!toDoHandler) || (!toCheckHandler)) return;
            if (typeof interval == 'undefined') interval = 1000;
            if (typeof times == 'undefined') times = 20;
        
            if (--times < 0) {
                if (typeof failHandler === 'function') {
                    failHandler();
                }
                return;
            }
            if (toCheckHandler()) {
                toDoHandler();
                return;
            }
        
            setTimeout(function () { ClickTaleSettings.PTC.doOnlyWhen(toDoHandler, toCheckHandler, interval, times, failHandler); }, interval);
        }
        ClickTaleSettings.PTC.doOnlyWhen(function () { 
            if (window.ClickTaleSettings.PTC.okToRunPCC) { 
                (function(){
                    window.ClickTaleSettings = window.ClickTaleSettings || {};
                    ClickTaleSettings.PTC = ClickTaleSettings.PTC || {};
                    ClickTaleSettings.PTC.originalPCCLocation = 'P33_PID82';
                    
                    var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function da(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}var ea="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var f in d)Object.prototype.hasOwnProperty.call(d,f)&&(a[f]=d[f])}return a};da("Object.assign",function(a){return a||ea});var fa;
function g(a,b,c,d,f){a&&b&&("undefined"==typeof c&&(c=1E3),"undefined"==typeof d&&(d=20),0>--d?"function"===typeof f&&f():b()?a():setTimeout(function(){g(a,b,c,d,f)},c))}function h(a){var b="someText".trim,c=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;fa=b&&!b.call(new String("\ufeff\u00a0"))?function(d){return null==d?"":b.call(d)}:function(d){return null==d?"":(d+"").replace(c,"")};return fa(a)}
function ha(a){if(!a)return!1;var b=a.getRootNode?a.getRootNode({composed:!1}):a.ownerDocument;return!!(a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_CONTAINS&&(a.offsetWidth||a.offsetHeight||a.getClientRects().length))}function ia(a){return"string"==typeof a?ia(document.querySelectorAll(a)):Array.prototype.filter.call(a,function(b){return ha(b)})};function ja(a,b){b||(b=document);return b instanceof Element||b instanceof Document?Array.prototype.slice.call(b.querySelectorAll(a)):"string"===typeof b?ja(a,document.querySelectorAll(b)):Array.isArray(b)||b instanceof HTMLCollection||b instanceof NodeList?Array.prototype.reduce.call(b,function(c,d){return c.concat(Array.prototype.slice.call(d.querySelectorAll(a)))},[]):[]}
function l(a,b){if(a&&a.nodeType&&9===a.nodeType)return!1;var c=Element.prototype;l=function(d,f){return d&&document.documentElement.contains(d)?l.matches.call(d,f):!1};l.matches=c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector||c.matches;return l(a,b)}function n(a,b){n=Element.prototype.closest?function(c,d){return c&&c instanceof Element?Element.prototype.closest.call(c,d):null}:function(c,d){for(;c&&!l(c,d);)c=c.parentElement;return c};return n(a,b)};var ka=!1,la=Object.defineProperty&&Object.defineProperty({},"passive",{get:function(){ka=!0}});document.addEventListener("test",function(){},la);var v=ka?{passive:!0,capture:!0}:!0,y=ka?{passive:!0,capture:!1}:!1;
function z(a){function b(){2==++c&&a()}if(!~z.s.indexOf(a)){z.s.push(a);var c=0;ma(b);if("function"==typeof ClickTaleIsRecording&&!0===ClickTaleIsRecording())b();else{var d=window.ClickTaleOnRecording||function(){};window.ClickTaleOnRecording=function(){b();return d.apply(this,arguments)}}}}z.s=[];function ma(a){function b(){c||(c=!0,a())}var c=!1;"loading"!=document.readyState?b():document.addEventListener&&document.addEventListener("DOMContentLoaded",b,!1)}
function A(a,b,c,d,f){if("string"===typeof b&&-1!=b.indexOf(" "))return b.split(/\s+/).forEach(function(e){return A(a,e,c,d,f)}),a;if("string"===typeof a)Array.prototype.forEach.call(document.querySelectorAll(a),function(e){A(e,b,c,d,f)});else if(a instanceof Array||a instanceof NodeList)Array.prototype.forEach.call(a,function(e){A(e,b,c,d,f)});else{var k="";"string"==typeof c&&("mouseenter"==b?(b="mouseover",k="mouseenter"):"mouseleave"==b&&(b="mouseout",k="mouseleave"));a.addEventListener(b,function(e,
q,x,m,w,r){return function(p){if("function"===typeof x)x.apply(this,arguments),w&&e.removeEventListener(q,arguments.callee,y);else{var t=p.relatedTarget,u=n(p.target,x);u&&e.compareDocumentPosition(u)&Node.DOCUMENT_POSITION_CONTAINED_BY&&("mouseenter"==r||"mouseleave"==r?t&&(t==u||u.compareDocumentPosition(t)&Node.DOCUMENT_POSITION_CONTAINED_BY)||m.apply(u,arguments):m.apply(u,arguments),w&&e.removeEventListener(q,arguments.callee,y))}}}(a,b,c,d,f,k),y)}return a}
function B(a,b,c,d,f){if("string"===typeof b&&-1!=b.indexOf(" "))return b.split(/\s+/).forEach(function(e){return B(a,e,c,d,f)}),a;if("string"===typeof a)Array.prototype.forEach.call(document.querySelectorAll(a),function(e){B(e,b,c,d,f)});else if(a instanceof Array||a instanceof NodeList)Array.prototype.forEach.call(a,function(e){B(e,b,c,d,f)});else{var k="";"string"==typeof c&&("mouseenter"==b?(b="mouseover",k="mouseenter"):"mouseleave"==b&&(b="mouseout",k="mouseleave"));a.addEventListener(b,function(e,
q,x,m,w,r){return function(p){if("function"===typeof x)x.apply(this,arguments),w&&e.removeEventListener(q,arguments.callee,v);else{var t=p.relatedTarget,u=n(p.target,x);u&&e.compareDocumentPosition(u)&Node.DOCUMENT_POSITION_CONTAINED_BY&&("mouseenter"==r||"mouseleave"==r?t&&(t==u||u.compareDocumentPosition(t)&Node.DOCUMENT_POSITION_CONTAINED_BY)||m.apply(u,arguments):m.apply(u,arguments),w&&e.removeEventListener(q,arguments.callee,v))}}}(a,b,c,d,f,k),v)}return a}
function na(a,b){document.addEventListener("mouseup",function(c){a===c.target&&b();document.removeEventListener("mouseup",arguments.callee,v)},v)}function oa(a,b){function c(d){document.removeEventListener("touchend",arguments.callee,v);a===d.target&&b()}document.addEventListener("touchend",c,v);document.addEventListener("touchmove",function(d){document.removeEventListener("touchmove",arguments.callee,v);document.removeEventListener("touchend",c,v)},v)}
function C(a,b){var c=D();c&&(c.m?C=oa:C=na,C(a,b))}function pa(a,b){if("string"===typeof a)Array.prototype.forEach.call(document.querySelectorAll(a),function(d){pa(d,b)});else if(a instanceof Array||a instanceof NodeList)Array.prototype.forEach.call(a,function(d){pa(d,b)});else{var c=document.createEvent("HTMLEvents");c.initEvent(b,!0,!0);return!a.dispatchEvent(c)}};function qa(a){if(window.CSS&&"function"===typeof window.CSS.escape)qa=function(d){return window.CSS.escape.call(window.CSS,d)};else{var b=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\x80-\uFFFF\w-]/g,c=function(d,f){return f?"\x00"===d?"\ufffd":d.slice(0,-1)+"\\"+d.charCodeAt(d.length-1).toString(16)+" ":"\\"+d};qa=function(d){return d.replace(b,c)}}return qa(a)}function ra(a){return btoa(encodeURIComponent(a).replace(/%([0-9A-F]{2})/g,function(b,c){return String.fromCharCode(+("0x"+c))}))};function sa(a){window._uxa=window._uxa||[];window._uxa.push.apply(window._uxa,arguments)}function ta(a){a=void 0===a?window.location.pathname+window.location.hash.replace("#","?__"):a;sa(["trackPageview",a])}function E(a,b){sa(["trackDynamicVariable",{key:a,value:b}])};var ua,va,wa,xa,ya=!1;function F(a){"function"===typeof ClickTaleExec&&ClickTaleExec(a)}function za(){"function"===typeof ClickTaleStop&&ClickTaleStop()}function G(a,b){"function"===typeof ClickTaleEvent&&(b?!0!==G.flags[a]&&(G.flags[a]=!0,ClickTaleEvent(a)):ClickTaleEvent(a))}G.flags={};function Ba(a){"function"===typeof ClickTaleRegisterFormSubmit&&ClickTaleRegisterFormSubmit(a)}function Ca(a){"function"===typeof ClickTaleRegisterFormSubmitSent&&ClickTaleRegisterFormSubmitSent(a)}
function Da(){var a=H;"function"===typeof ClickTaleRegisterFormSubmitSuccess&&(a?ClickTaleRegisterFormSubmitSuccess(a):ClickTaleRegisterFormSubmitSuccess())}function Ea(a){"function"===typeof ClickTaleRegisterFormSubmitFailure&&(a?ClickTaleRegisterFormSubmitFailure(a):ClickTaleRegisterFormSubmitFailure())}function Fa(a,b,c){return"function"===typeof window.ClickTaleLogicalForm?window.ClickTaleLogicalForm(a,b,c):0}
function Ga(a,b){a&&"object"==typeof a&&"string"==typeof b&&(window.ClickTaleContext&&-1!=document.referrer.indexOf(location.hostname)&&window.parent.ct&&window.parent.ct.ElementAddressing&&"function"===typeof window.parent.ct.ElementAddressing.forceSetCustomElementID?window.parent.ct.ElementAddressing.forceSetCustomElementID(a,b):(window.ClickTaleContext||"function"!==typeof ClickTaleSetCustomElementID||-1==ClickTaleSetCustomElementID.toString().indexOf("duplicate registration of custom id")?window.ClickTaleSetCustomElementID=
window.ClickTaleSetCustomElementID||function(c,d){c.ClickTale=c.ClickTale||{};c.ClickTale.CustomID=d}:Ga=function(c,d){c.ClickTale=c.ClickTale||{};c.ClickTale.CustomID=d},window.ClickTaleSetCustomElementID(a,b)))}
function Ha(){Array.prototype.forEach.call(document.querySelectorAll('[id]:not([id=""])'),function(a){if(!l(a,'input[type="hidden"], script')){var b=a.getAttribute("id");b.match(/(?:\r|\n)/)&&"function"===typeof ClickTaleNote&&ClickTaleNote("ctlib.api.SetCustomElementIdDuplicates: ids with line break found!");a=document.querySelectorAll('[id="'+qa(b)+'"]');var c=Ia;1<a.length&&!c[b]&&(c[b]=!0,Array.prototype.forEach.call(a,function(d,f){Ga(d,b.replace(/(\r|\n|\r\n|\s+)+/g,"_").replace(/\W/g,"_")+
"_"+f)}))}})}var Ia={};function Ja(a,b){"function"===typeof ClickTaleLogical&&(G.flags={},Ia={},I.h&&I.h instanceof Ka&&I.h.clear(),b?ClickTaleLogical(a,b):ClickTaleLogical(a))}function D(){if("function"===typeof ClickTaleDetectAgent){var a=ClickTaleDetectAgent();if(a)return D=function(){return a},D()}return null}function La(){"function"===typeof ClickTaleUploadPage&&ClickTaleUploadPage(void 0,void 0)}
function Ma(a){if("function"===typeof ClickTaleRegisterTouchAction){var b=a.getBoundingClientRect();ClickTaleRegisterTouchAction(a,b.left+document.body.scrollLeft,b.top+document.body.scrollTop)}}
function Na(a,b,c){if("boolean"!=typeof Oa){var d=D();d&&(Oa=!!d.m)}a||(a="mousedown",Oa&&(a="touchstart"));c=c||"img, a, button, textarea, input, select";Oa&&(c+=", label[for]");B(document,a,c,function(f){var k=f.target,e=this;if(!b||!l(this,b))if(Oa)if(l(this,"label[for]"))C(k,function(m){return function(){var w,r;(w=m.getAttribute("for"))&&(r=document.getElementById(w))&&Ma(r)}.bind(e)}(k,f));else{var q=-1,x=function(m){clearTimeout(q);document.removeEventListener("touchstart",arguments.callee,
y);C(k,function(w){return function(){function r(t){document.removeEventListener("touchend",arguments.callee,y);clearTimeout(p)}var p=-1;document.addEventListener("touchend",r,y);p=setTimeout(function(){document.removeEventListener("touchend",r,y);Ma(w)},50)}.bind(e)}(k,f))};document.addEventListener("touchstart",x,y);q=setTimeout(function(){document.removeEventListener("touchstart",x,y);Ma(k)},50)}else C(k,function(m,w){return function(){function r(t){t.target===m&&(Pa=!0);document.removeEventListener("click",
arguments.callee,!0);clearTimeout(p)}var p=setTimeout(function(){Pa||"function"===typeof window.ClickTaleRegisterElementAction&&ClickTaleRegisterElementAction("click",w);document.removeEventListener("click",r,!0);Pa=void 0},200);document.addEventListener("click",r,!0)}.bind(e)}(k,f))})}var Oa,Pa;
function Qa(a,b,c,d){Qa.o&&(Qa.o=!1,d=d||400,"number"==typeof c&&(d=c,c=""),b=b||document.location.href,za(),window.ClickTaleIncludedOnDOMReady=!0,window.ClickTaleIncludedOnWindowLoad=!0,La(),Ja(b,c),g(a,ClickTaleIsRecording,1E3,2),setTimeout(function(){Qa.o=!0},d))}Qa.o=!0;
function Ra(a){var b=Sa,c=Ta,d=Ua;if(Va){Va=!1;var f=f||400;d?(za(),window.ClickTaleIncludedOnDOMReady=!0,window.ClickTaleIncludedOnWindowLoad=!0,La(),Ja(a.href,c)):(Array.isArray(window.ClickTaleOnStop)&&window.ClickTaleOnStop.forEach(function(k){if("function"===typeof k)try{k.call(window)}catch(e){}}),ta(a.pathname));b();clearTimeout(Wa);Wa=setTimeout(function(){Va=!0},f)}}var Wa=-1,Va=!0;
function Xa(a){"function"===typeof ClickTaleAddAugmentElementPathHandler&&ClickTaleAddAugmentElementPathHandler("Linkanalytics",a)}var Ya=[];
function Ka(){this.l=!1;this.g="";this.init=function(a){this.l||(this.l=!0,document.addEventListener("input",this.u,v));this.B(a);this.g=this.g?this.g+","+a:a};this.u=function(a){a=a.target;if(l(a,this.g)){var b=ja(this.g).indexOf(a);F("document.querySelectorAll('"+this.g+"')["+b+"].value = Base64Decode('"+ra(a.value)+"');")}}.bind(this);this.B=function(a){var b="";ja(a).forEach(function(c,d){b+="document.querySelectorAll('"+a+"')["+d+"].value = Base64Decode('"+ra(c.value)+"'); "});b&&F(b)};this.clear=
function(){document.removeEventListener("input",this.u,v);this.l=!1;this.g=""}}function I(a){I.h=I.h||new Ka;I.h.init(a)}I.h=null;var J=G,K=A,Za=B,$a=pa,L=Ga;function M(a,b){return a instanceof Element?b instanceof Element?a===b:l(a,b):!1}var O=n,P=ia,ab=C;var Ua=!1,Q="",R="",cb=!1,db=!0,Ta=location.href,S=!1,T=!1,H=null,U=null,eb=!1,V,W="",fb=!1,X={name:"Agent Name",email:"Agent Email",phone:"Agent Phone",thank_you:"Thank You",agent:"Agent",consumer:"Home b_s",pro:"Prof"},gb=[{j:/\//i,location:location.pathname,i:"Overview"},{j:/\/padirect\//i,location:location.pathname,i:"Agent Direct"},{j:/\/products\/concierge\//i,location:location.pathname,i:"Agent Concierge"},{j:/\/products\/agent-account\//i,location:location.pathname,i:"Agent Account"},{j:/\/contact\//i,
location:location.pathname,i:"Contact"}];function hb(a,b){g(function(){ib(b)},function(){return!!ha(document.querySelector(a))},250,25)}(function(a){Ya=a;var b="";a.forEach(function(c){!0===c[1]&&(b+=","+c[0])});b&&Na("","",b.replace(/^,/,""));Xa(function(c){return function(d){for(var f=0,k=c.length;f<k;f++){var e=c[f],q=e[0];if(d&&l(d,q)&&(q=e[2],"function"!=typeof q||q()))return{data:{interesting:e[1]}}}return null}}(Ya))})([["span.btnPrimary , .goldberg-faqs dt",!0]]);
function jb(){var a=document.querySelector(".starfox-modal--active .slick-current .starfox-heading");return a&&(a=a.textContent.trim())?(a=a.toLowerCase().split(/[!?.]/)[0].replace(/\s/g,"-"),a.replace(/what's/i,"what-is")):""}function kb(){fb||(fb=!0,g(function(){fb=!1;J("Google Sign-In Modal")},function(){return!!document.querySelector('div[id="credential_picker_container"]')},250,50,function(){fb=!1}))}
function ib(a){a=void 0===a?"":a;var b=Object.assign({},document.location);a&&(a="__"+a,0>b.href.indexOf("#")&&(a="?"+a));b.href=b.href.replace("#","?__")+a;b.pathname+=b.hash.replace("#","?__")+a;Ra(b)}function lb(a){var b="";a&&"string"==typeof a&&(a=document.querySelector(a));a&&a instanceof HTMLElement&&(b=a.textContent||a.innerText||a.value||"")&&(b=h(b.replace(/\s+/g," ")));return b}function Y(a){a&&"string"===typeof a&&J(a)}
function Z(a){a&&"string"==typeof a&&(a=document.querySelectorAll(a));if(a instanceof NodeList)for(var b=0;b<a.length;b++)if(Z(a[b]))return!0;return a instanceof Element?!!(a&&a.compareDocumentPosition(document)&Node.DOCUMENT_POSITION_CONTAINS&&(0<a.offsetWidth&&0<a.offsetHeight||0<a.getClientRects().length)):!1}
function mb(){g(function(){var a=window.ga.getAll();"object"===typeof a&&0<a.length&&((a=a[0].get("dimension12"))?(E("GAdimension12",a),J("Onload | "+a),/(?:consumer|agent)/i.test(a)?(E("User Status","logged in user"),Y("Onload | logged in user")):E("User Status","Not Logged in user")):J("Onload | Unrecognized"))},function(){return"function"===typeof window.ga&&"function"===typeof window.ga.getAll},100,60)}
function nb(){if("boolean"===typeof cb){var a=cb.toString();"function"===typeof ClickTaleField&&ClickTaleField("isMobile",a)}}
function ob(){-1<R.indexOf("/products/advertising/")&&g(function(){P(".goldberg-section.optimizely-v1").length?(Y("Onload | Zillow Contact Us Version B"),V="vB"):P(".goldberg-section.optimizely-v2").length?(Y("Onload | Zillow Explore Pricing version C"),V="vC"):P(".goldberg-section.optimizely-original").length&&(E("Get Started Control","Get Started Control"),Y("Onload | Zillow Get Started Control"),V="vControl")},function(){return 0<P("#jumbotron a").length},1E3,5)}
function pb(){var a;g(function(){var b=a[0];M(b,".js-available-package-blurb")?(Y("onload | here\u2019s what available"),E("here\u2019s what available","here\u2019s what available")):M(b,".js-limited-package-blurb")?Y("Onload | Availability is limited"):M(b,".js-unavailable-package-blurb")?Y("Onload | No Advertising availability found"):M(b,".js-other-zips-package-blurb")&&(b=document.querySelector(".js-other-zips-package-blurb .js-other-package-zips"))&&(-1<b.innerText.indexOf("and")?(Y("Onload | no availability 2+ recommendations"),
E("no availability 2+ recommendations","no availability 2+ recommendations")):Y("Onload | no availability 1 recommendation"))},function(){a=P(".js-available-package-blurb,.js-other-zips-package-blurb,.js-limited-package-blurb,.js-unavailable-package-blurb");return 0<a.length},1E3,5)}
function qb(){K(document,"keydown",'#viewPricingBtn,.modal-body input[name="fullName"],.modal-body input[name="tfa_Email"],.modal-body input[name="tfa_Phone"],#zipcodeInput,input#fullName,input#tfa_Email,input#tfa_Phone',function(a){if("vControl"==V||"vB"==V)M(this,'.modal-body input[name="fullName"]')?J("Action | Get Started Modal | Name",!0):M(this,'.modal-body input[name="tfa_Email"]')?J("Action | Get Started Modal | Email",!0):M(this,'.modal-body input[name="tfa_Phone"]')&&J("Action | Get Started Modal | Phone",
!0);"zipcode"==V&&(M(this,"#zipcodeInput")?(J("Action | Explore your options | zip code field",!0),"Enter"!=a.key&&13!=a.keyCode||document.querySelector("#viewPricingBtn[disabled]")||J("Action | Explore your options | view pricing",!0)):"Enter"!=a.key&&13!=a.keyCode||!M(this,"#viewPricingBtn")||J("Action | Explore your options | view pricing",!0));"ContactUsForm"==V&&(M(this,"input#fullName")?J("Action | contact us | name",!0):M(this,"input#tfa_Email")?J("Action | contact us | email",!0):M(this,"input#tfa_Phone")&&
J("Action | contact us | phone number",!0))})}function rb(){setTimeout(function(){P(".modal-body input.form-control").length&&Y("Onload | Get started Modal")},500)}function sb(){setTimeout(function(){P(".modal-body a.text-success").length&&Y("Onload | Get Started Modal | Confirmation")},500)}
function tb(){var a,b,c,d;g(function(){b=1!=a.length||document.querySelector(".pa-contentBlock .pa-dataValue")?"PA":"Non PA";d=1==c.length?"License number exist":"No License number";E("License number Status",d);E("PA Status",b);J("Onload | Dashboard | "+b);J("Onload | Dashboard | "+d)},function(){a=document.querySelectorAll(".pa-buttonRow .pa-button");c=document.querySelectorAll(".pa-cardLine a.analyticsCTA");return!!a.length&&!!c.length},200,10)}
function Sa(){Ha();Q="";Ta=location.href;R=document.location.pathname.toLowerCase();if(db)db=!1;else for(var a=window.ClickTaleSettings&&window.ClickTaleSettings.PTC&&window.ClickTaleSettings.PTC.InitFuncs?window.ClickTaleSettings.PTC.InitFuncs:[],b=0,c=a.length;b<c;b++)if("function"===typeof a[b])a[b]();Ua?nb():z(function(){Ua=!0;nb()});kb();mb();/premieragent.zillow.com\/products\/advertising\//i.test(location.href)?Q="Advertising":"/get-more-real-estate-leads-updated"==R?Q="Get More Leads":/\/agent-resources\//i.test(location.pathname)?
(Q="Agent Resources",/download\/open-houses-5-ways-drive-traffic\//i.test(location.pathname)&&(Q+=" - Get free download form",Z(".btn-primary.download")&&(Q+=" - Success"))):Array.prototype.forEach.call(gb,function(q){q.j.test(q.location)&&(Q=q.i)});if(Q){J("Onload | "+Q,!0);if(Z("#signup-form")&&(S=!0,J('Onload | "sign up" form',!0),E("sign up form","sign up form"),a=document.querySelectorAll("#fullName, #tfa_5, #tfa_6"),0<a.length))for(b=0;b<a.length;b++)if(a[b].value){E("Pre-filled form","Pre-filled form");
J("Onload | Pre-filled form",!0);break}if(0<document.querySelectorAll(".lead-gen-form>form").length&&(T=!0,a=document.querySelectorAll('[id="tfa_FirstName"], [id="tfa_LastName"], [id="tfa_Email"], [id="tfa_Phone"]'),0<a.length))for(b=0;b<a.length;b++)if(a[b].value){J("Onload | Pre-filled form",!0);break}"Agent Account"==Q&&(b="",0<document.querySelectorAll('a[href*="/Register/"]').length&&(b="Not"),E("User Status",b+" Logged in user"),Y("Onload | "+Q+" | "+b+" Logged in user"))}"/get-more-leads-thank-you.html"==
R&&Y("Onload | Get More Leads | Thank You");R.indexOf("dashboard")&&tb();ub();(T||S)&&vb();-1<R.indexOf("zipcode")?(Y("Onload | Explore Your Option \u2013Enter Zip"),E("Explore Your Option \u2013Enter Zip","Explore Your Option \u2013Enter Zip"),V="zipcode"):-1<R.indexOf("recommended")?(E("What\u2019s available in your area modal","What\u2019s available in your area modal"),Y("Onload | What\u2019s available in your area modal"),pb(),V="recommended"):-1<R.indexOf("inbound_form")&&(Y("Onload | contact us"),
V="ContactUsForm");ob();var d=document.querySelector("div.goldberg-modal");if(d)if(d.classList.contains("show"))Y("OL | PA Advertising | Getting Started Modal"),wb();else if(window.MutationObserver){var f=new window.MutationObserver(function(){d&&d.classList.contains("show")&&(f.disconnect(),Y("OL | PA Advertising | Getting Started Modal"),wb())});b={attributes:!0,attributeFilter:["class"]};f&&"function"===typeof f.observe&&d&&f.observe(d,b)}if(/\/premier\-agent\//i.test(R)||/\/z\/rental\-property\-advertising\//i.test(R)){var k=
document.querySelector('form[data-ga_category="zpa|form"], form[data-ga_category="rentals_mf|form"]');if(k&&k.querySelector("input")&&window.MutationObserver){var e=new window.MutationObserver(function(){k&&k.querySelector("h2.apex-form-success")&&(e.disconnect(),ib("submission_confirmation"))});b={childList:!0};e&&"function"===typeof e.observe&&e.observe(k,b)}}}
function wb(){if(window.MutationObserver){var a=new window.MutationObserver(function(){if(c){c.querySelector("div.slick-track > div.slick-slide")!==d&&(d=c.querySelector("div.slick-track > div.slick-slide"))&&L(d,"firstStep");var f=c.querySelector("div.slick-active div[data-step], div.slick-active div[data-path]");if(f){var k=f.getAttribute("data-step")||f.getAttribute("data-path");k&&X[k]&&W!=X[k]&&("pro"!=k&&"consumer"!=k||L(f,k),W=X[k],Y("A | PA Advertising | "+X[k]))}}}),b={attributes:!0,attributeFilter:["style"]},
c=document.querySelector("div.goldberg-modal div.slick-list");if(a&&"function"===typeof a.observe&&c){var d=c.querySelector("div.slick-track > div.slick-slide");d&&L(d,"firstStep");a.observe(c,b)}}}
function vb(){if(!xb){xb=!0;var a=[],b="",c=[];S&&(b="Sign up",a=Array.prototype.slice.call(document.querySelectorAll("#pro-type-select, #fullName, #tfa_5, #tfa_6, #roleSelect, #teamSizeSelect")),c=Array.prototype.slice.call(document.querySelectorAll("#formSubmitButton")));if(T){var d=document.querySelectorAll(".lead-gen-form>form");if(0<d.length){b="Download form";a=Array.prototype.slice.call(d[0].querySelectorAll('select[name="user_type"], [id="tfa_FirstName"], [id="tfa_LastName"], [id="tfa_Email"], [id="tfa_Phone"]'));
c=Array.prototype.slice.call(d[0].querySelectorAll(".btn-primary"));var f=[],k="",e=[];2==d.length&&(k="Download form 2",f=Array.prototype.slice.call(d[1].querySelectorAll('select[name="user_type"], [id="tfa_FirstName"], [id="tfa_LastName"], [id="tfa_Email"], [id="tfa_Phone"]')),e=Array.prototype.slice.call(d[1].querySelectorAll(".btn-primary")))}}0<a.length&&"string"==typeof b&&0<c.length&&("function"===typeof ClickTaleFormDisableAll&&ClickTaleFormDisableAll(),H=Fa(b,a,c),T&&0<f.length&&"string"==
typeof k&&e&&0<e.length&&(U=Fa(k,f,e)))}}var xb;
function yb(){var a=!1,b=!1;g(function(){a&&(J("Action | "+Q+" | Validation Error"),S?(H&&Ea(H),Array.prototype.forEach.call(document.querySelectorAll(".fieldWarning input[placeholder], .fieldWarning select>option[disabled]"),function(c){var d="";M(c,"input[placeholder]")&&(d=c.getAttribute("placeholder"));M(c,"option[disabled]")&&(d=M(c,"#pro-type-select>option[disabled]")?'"I am"':c.textContent);d&&J("Action | "+Q+" | Validation Error | "+d,!0)})):T&&(H&&(Z(".visible-xs .error")||Z(".visible-xs .lead-gen-form>form input:invalid"))&&
Ea(H),U&&(Z(":not(.visible-xs) .error")||Z(":not(.visible-xs) .lead-gen-form>form input:invalid"))&&Ea(U)));b&&(J("Action | "+Q+' | "Sign Up" form submitted Successfuly',!0),H&&Da())},function(){S?(a=Z(".fieldWarning"),b=Z("#thank-you-div")):T&&(a=Z(".error")||Z(".lead-gen-form>form input:invalid"));return(S||T)&&(a||b)},1E3,10)}
function zb(){T?(J("Action | "+Q+" | Download form submitted",!0),H&&Z(".visible-xs .lead-gen-form>form")&&(Ba(H),Ca(H)),U&&(Ba(U),Ca(U))):S&&(H&&(Ba(H),Ca(H)),J("Action | "+Q+' | "Sign Up" form submitted',!0),Z("#teamSizeSelect")&&J("Action | "+Q+' | "Sign Up" form submitted - with team size',!0));yb()}
function ub(){if(T){var a=0;Array.prototype.forEach.call(document.querySelectorAll(".lead-gen-form>form"),function(c){L(c,"downloadform_"+a);a++});a=0;Array.prototype.forEach.call(document.querySelectorAll('select[name="user_type"]'),function(c){L(c,"iam_"+a);a++})}var b=document.querySelector('div.goldberg-modal div[id*="paxl-widget-multistep"]');b&&L(b,"goldberg-modal")}
function Ab(){if(!window.ClickTaleFirstPCCGo){window.ClickTaleFirstPCCGo=!0;var a=D();a&&(cb=a.m);Sa();a="#header-nav a";if(S)a+=", #formSubmitButton, .consumer-zillow-links a, .pro-zillow-links a";else if("Agent Account"==Q)a+=", a.btn[gelement]";else if(T)a+=", .lead-gen-form>form .btn-primary";else if("Advertising"==Q||"Get More Leads"==Q)a+=", button#formSubmitButton";else if(R.match(/\/premier-agent\/solutions\/(real-estate-agent|real-estate-team)\//)||-1<R.indexOf("/premier-agent/connect-live-leads/")||
"/premier-agent/"==R||-1<R.indexOf("/rental-property-advertising/"))a+=",.starfox-button, .starfox-modal .starfox-modal a, .starfox-modal button, .starfox-modal label";qb();a+=',#jumbotron a.goldberg-link,.modal-body input.btn,.goldberg-section.optimizely-v1 a,#jumbotron a#optimizely-v1-cta,.goldberg-section.optimizely-v2 a,#viewPricingBtn,.goldberg-section.optimizely-original a,.modal-body input[value="Get started"],button[glabel="edit_zip"],.mapboxgl-canvas,span[data-tooltip*=\'The average\'],span[data-tooltip*=\'ZIP codes\'],span[data-tooltip*=\'The amount\'],span[data-tooltip*=\'The estimated\'],span[data-tooltip*=\'The total\'],button.js-btn-proceed,button.js-btn-customize-package,button.js-btn-contact-us,input[type="number"],button.change-zip-button,#formSubmitButton,a[glabel="close"],.btn-join-waitlist,#zipcodeInput,div.goldberg-modal div[data-path] button, div.goldberg-modal div[data-path] li >a[class*="list-item"],a[title="Go to Zillow"],[class*="starfox-button--primary"],.starfox-modal__content .btn.btn-primary, button[title="Sign in"], button[title="Join"], [href*="/user/acct/login"]';
var b=cb?"touchstart":"mousedown";a&&Za(document,b,a,function(c){var d=c.target;ab(d,function(f,k,e){return function(){if((R.match(/\/premier-agent\/solutions\/(real-estate-agent|real-estate-team)\//)||-1<R.indexOf("/premier-agent/connect-live-leads/")||"/premier-agent/"==R||-1<R.indexOf("/rental-property-advertising/"))&&M(e,".starfox-button, .starfox-modal a, .starfox-modal, .starfox-modal button, .starfox-modal label")){var q=jb(),x="";g(function(){ib(x)},function(){x=jb();return x!=q},250,40)}-1<
R.indexOf("/rental-property-advertising/")&&O(f,'input[name="Original_Company_Name"]')&&hb('input[name="Original_Company_Name"]',"What_is_your_company_name_and_location");-1<R.indexOf("/rental-manager/")&&O(f,'a[title="Go to Zillow"]')&&ib("go-to-zillow-link");if(R.match(/\/rental-property-advertising\/(lease-connect|rent-connect)\//)){var m=R.match("lease-connect")?"Lease":"Rent";O(f,'[class*="starfox-button--primary"]')?hb(".starfox-modal__content .btn.btn-primary",m+"_Connect_Form_Start"):O(f,
".starfox-modal__content .btn.btn-primary")&&hb(".apex-form-success",m+"_Connect_Thank_You")}R.match(/\/solutions\/real-estate-broker\//)&&(O(f,'[class*="starfox-button--primary"][data-ga-action="modal_open"]')?hb(".starfox-modal__content .btn.btn-primary","Broker_Solution_Form_Start"):O(f,".starfox-modal__content .btn.btn-primary")&&hb(".apex-form-success","Broker_Solution_Thank_You"));if(W&&(M(e,"div.goldberg-modal div[data-path] button")&&(m=h(e.textContent))&&Y("A | PA Advertising | "+W+" | "+
m),M(e,'div.goldberg-modal div[data-path] li >a[class*="list-item"]')&&(m=O(e,"div[data-path]")))){var w=m.getAttribute("data-path");if((m=h(e.textContent))&&w){var r=m.split(" ");"consumer"==w?m=r[0]:"pro"==w&&(m=r[r.length-1]);m&&Y("A | PA Advertising | "+W+" | "+m)}}O(e,'button[title="Sign in"], button[title="Join"], [href*="/user/acct/login"]')&&(kb(),g(function(){J("Zillow Sign-In Modal")},function(){return!!document.querySelector("#reg-login .act-auth-container, #login-anchor .act-auth-container")},
150,40));V&&("zipcode"==V?M(e,"#viewPricingBtn")?(Y("Action | Explore your options | view pricing"),$a(document.body,"keydown")):M(e,"#zipcodeInput")&&J("Action | Explore your options | zip code field",!0):"vControl"==V?M(e,"#jumbotron a.goldberg-link")?(Y("Action | Control | Get Started"),rb()):M(e,".goldberg-section.optimizely-original a")?(Y("Action | Control | Contact us"),rb()):M(e,'.modal-body input[value="Get started"]')&&(Y("Action | Get started Modal | Get Started"),sb()):"vB"==V?M(e,"#jumbotron a.goldberg-link")?
(Y("Action |  Version B | Get started -hero"),rb()):M(e,"#jumbotron a#optimizely-v1-cta")?Y("Action |  Version B | Explore Pricing -hero"):M(e,'.goldberg-section.optimizely-v1 a[href="#modal"]')?(Y("Action |  Version B | Contact Us -upsell"),rb()):M(e,'.goldberg-section.optimizely-v1 a[href*="zipcode"]')?Y("Action |  Version B | Explore Pricing \u2013upsell"):M(e,'.modal-body input[value="Get started"]')&&(Y("Action | Get started Modal | Get Started"),sb()):"vC"==V?M(e,"#jumbotron a.goldberg-link")?
Y("Action |  Version C | Explore Pricing -hero"):M(e,'.goldberg-section.optimizely-v2 a[href*="zipcode"]')&&Y("Action |  Version C | Explore Pricing \u2013 upsell"):"recommended"==V?M(e,'button[glabel="edit_zip"]')?Y("Action | Availability modal | edit"):M(e,".mapboxgl-canvas")?Y("Action | Clicked on map"):M(e,"span[data-tooltip*='ZIP codes']")?Y("Action | Available in your area | Zip"):M(e,"span[data-tooltip*='The average']")?Y("Action | Available in your area | Avg home $"):M(e,"span[data-tooltip*='The amount']")?
Y("Action | Available in your area | Budget"):M(e,"span[data-tooltip*='The estimated']")?Y("Action | Available in your area | Est ROI"):M(e,"span[data-tooltip*='The total']")?Y("Action | Available in your area | Total"):M(e,"button.js-btn-proceed")?Y("Action | Availability modal| proceed"):M(e,"button.js-btn-customize-package")?Y("Action | Availability modal| customize"):M(e,"button.js-btn-contact-us")?Y("Action  |available in your area | contact us"):M(e,'input[type="number"]')?Y("Action | Available In Your Area Modal | zip code"):
M(e,"button.change-zip-button")?Y("Action | Availability modal | ok"):M(e,'a[glabel="close"]')?Y("Action | Click on x"):M(e,".btn-join-waitlist")&&Y("Action | Availability modal | Join waitlist"):"ContactUsForm"==V&&M(e,"#formSubmitButton")&&Y("Action | contact us | clicked contact us"));M(e,"#header-nav a")&&(m=O(e,".menu-item"))&&(m=m.querySelector("a.nav-link"))&&(M(f,".dropdown-item")?(w=lb(f))&&Y("Action | Top Nav | "+m+" | Clicks "+w):Y("Action | Top Nav | Clicks "+m));S?M(e,"#formSubmitButton")?
(J("Action | "+Q+" | Clicked on Get Started",!0),Z("#teamSizeSelect")&&J("Action | "+Q+" | Clicked on Get Started - with team size",!0),zb()):M(e,".pro-zillow-links a")?M(e,"#thank-you-div .pro-zillow-links a")?J("Action | "+Q+' | Clicked on any "While your\u2019e waiting" option',!0):(J("Action | "+Q+' | Clicked on any "other professional" option',!0),J("Action | "+Q+" | Didn\u2019t submit the Sign Up form",!0)):M(e,".consumer-zillow-links a")&&(J("Action | "+Q+' | Clicked on any "Home buyer / seller" option',
!0),J("Action | "+Q+" | Didn\u2019t submit the Sign Up form",!0)):"Agent Account"==Q?M(e,"a.btn[gelement]")&&(m=f.textContent)&&(O(f,"#signup")&&(m+=" (bottom)"),J("Action | "+Q+' | Clicked on "'+h(m)+'"',!0)):T&&M(e,".btn-primary")&&(J("Action | "+Q+" | Clicked on Download",!0),zb());"Advertising"==Q?M(e,"button#formSubmitButton")&&(Y("Action | Advertising | Form | Clicked Get Started"),setTimeout(function(){if(document.querySelector("div#form-errors-top")&&"none"!=window.getComputedStyle(document.querySelector("div#form-errors-top"),
null).display){Y("Action | Advertising | Form | Validation Error");for(var p=document.querySelectorAll("ul.fieldGroup>li.fieldWarning select>option[disabled], ul.fieldGroup>li.fieldWarning input[placeholder]"),t=0;t<p.length;t++){var u=M(p[t],"#pro-type-select>option[disabled]")?"I am...":p[t].innerText||p[t].attributes.placeholder.value;u&&Y("Action | Advertising | Form | Validation Error | "+u)}}else document.querySelector("div#thank-you-div")&&"none"!=window.getComputedStyle(document.querySelector("div#thank-you-div"),
null).display&&Y("Action | Advertising | Form | Form Submitted Successfully")},2E3)):"Get More Leads"==Q&&M(e,"button#formSubmitButton")&&(Y("Action | Get More Leads | Form | Clicked Get Started"),setTimeout(function(){if(document.querySelector("div#form-errors-top")&&"none"!=window.getComputedStyle(document.querySelector("div#form-errors-top"),null).display){Y("Action | Get More Leads | Form | Validation Error");for(var p=document.querySelectorAll('form#contact-form-top select[name="real-estate-pro-type"].error,form#contact-form-top input[placeholder].error'),
t=0;t<p.length;t++){var u=M(p[t],'select[name="real-estate-pro-type"]')?"I am...":p[t].attributes.placeholder.value;u&&Y("Action | Get More Leads | Form | Validation Error | "+u)}}},2E3))}.bind(e)}(d,c,this))});if(S||T)K(document,"change",'#pro-type-select, #roleSelect, select[name="user_type"]',function(c){c=c.target;M(c,"#pro-type-select")||M(c,'select[name="user_type"]')?J("Action | "+Q+' | Selected  "I am"',!0):M(c,"#roleSelect")&&J("Action | "+Q+' | Selected "what is your role"',!0)}),K(document,
"keypress","#signup-form, .lead-gen-form>form",function(c){"Enter"!=c.key&&13!=c.keyCode||zb()});/premieragent.zillow.com\/pa\//i.test(location.href)&&1==document.querySelectorAll("#nav .dropdown").length&&(K("#nav .dropdown","mouseenter",function(){F("dropdownState('block')")}),K("#nav .dropdown","mouseleave",function(){F("dropdownState('none')")}));Array.prototype.forEach.call(["[id='header-search-input']"],function(c){var d=document.querySelector(c);d&&(d=d.value,(d=h(d))&&F('jQuery("'+c+'").val(unescape("'+
escape(d)+'"));'),K(document,"input",c,function(){var f=this.value;(f=h(f))&&F('jQuery("'+c+'").val(unescape("'+escape(f)+'"));');"[id='header-search-input']"==c&&J("Action | "+(Q?Q+" | ":"")+"Interacted with the Search Field",!0)}))});document.querySelector("select.pro-type-select")&&K(document,"change","select.pro-type-select",function(){if(document.querySelector("select.pro-type-select").value){var c=document.querySelector("select.pro-type-select").value;"agent"==c?Y("CEC | Action | Select Agent/Broker"):
"consumer"==c&&Y("CEC | Action | Select Home Buyer/Seller")}});A(document,"input",'div.real-estate-pro-types input[type="radio"]',function(){if(M(this,'div.real-estate-pro-types input[type="radio"]')&&W){var c=this.getAttribute("value");c&&X[c]&&Y("A | PA Advertising | Get Started | Click "+X[c])}});window.addEventListener("scroll",function(){!eb&&window.pageYOffset>document.body.offsetHeight/2&&(Y("Action | Site Wide | Scrolls 50% of Page"),eb=!0)})}}z(function(){Na();Ab()});
function Bb(){var a=Object.assign({},document.location);a.href=a.href.replace("#","?__");a.pathname+=a.hash.replace("#","?__");return a}window.clickTaleStartEventSignal=function(a){Ra(Bb());a&&"string"===typeof a&&J(a)};window.clickTaleEndEventSignal=function(){va&&(history.replaceState=va);wa&&(history.pushState=wa);xa&&window.removeEventListener("popstate",xa,!1);za()};
(function(a,b,c,d,f,k,e,q,x,m,w){function r(){"function"===typeof w&&w();var N=q?q():location;ya?Qa(function(){"function"===typeof a&&a()},N.href,t,c):ua&&(ta(N.pathname),!0===x&&"function"===typeof a&&a());t=N.href}function p(N){if(u&&(u=!1,setTimeout(function(){u=!0},e),"function"!==typeof k||k()))if(isNaN(f)||"number"!=typeof f||N){if("function"===typeof ClickTaleIsRecording&&ClickTaleIsRecording())ya=!0,za();else{var Aa;"function"!==typeof ClickTaleStop&&(Aa=window.ClickTaleOnStop)&&Array.isArray(Aa)&&
Aa.forEach(function(bb){"function"===typeof bb&&bb.call(window)});ua=!0}d()||(b?"string"===typeof b?g(r,function(){return!!document.querySelector(b+"")},1E3,10,r):"function"===typeof b?g(r,b,1E3,10,r):setTimeout(r,2E3):setTimeout(r,2E3))}else N=f||0,setTimeout(p.bind(null,!0),N)}"function"!=typeof a&&a&&(b=a.M,c=a.K,d=a.F,f=a.D,k=a.J,e=a.L,q=a.C,x=a.I,m=a.G,w=a.H,a=a.A);m=m||!1;d=d||function(){return!1};a=a||function(){};e=e||400;var t=(q?q():location).href;c||isNaN(b)||(c=b,b="");c=c||2E3;var u=
!0;window.history&&(va=history.replaceState,history.replaceState=function(){m?p():setTimeout(p,5);return va.apply(history,arguments)},wa=history.pushState,history.pushState=function(){m?p():setTimeout(p,5);return wa.apply(history,arguments)},xa=function(){m?p():setTimeout(p,5)},window.addEventListener("popstate",xa,!1))})({A:Sa,C:Bb});
                })();
            } 
        }, function () { return !!(window.ClickTaleSettings && ClickTaleSettings.PTC && typeof ClickTaleSettings.PTC.okToRunPCC != 'undefined'); }, 500, 20);


//Signature:hUuwOyzZJyCKNk235drYSTg+I7X4Xu9gk1oTX/afVQhNatZdnYdrXm7Onc9MeXDYR08ahannaGeR4JKikbd3gbzrNuvfKHE3JrglV0dVjUmML8MORcci6FNt2J31m/egutoMU5uPTUxyAZv+aPOZ+Z3v9yGU8Io9pbAADc5Ew6E=